---
# Based on the example from
#    https://gitlab.com/pages/jekyll/blob/master/.gitlab-ci.yml
image: ruby:latest

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
   - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
