---
# Site settings
title: "Trevor Keller, Ph. D."
description: "Professional résumé and CV of Trevor Keller, Ph. D."

# Build settings
markdown: kramdown
exclude: LaTeX
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:               "false"
resume_name:                 "Trevor Keller, Ph. D."
resume_title:                "Materials Research Scientist"
resume_contact_email:        "tkellerphd@gmail.com"
resume_header_contact_info:  "tkellerphd@gmail.com"
resume_summary: >
  Specializing in phase-field models of solid state coarsening phenomena. Passionate about software
  development for scientific computing. Interested in opportunities to help scientists learn to use
  high-performance computing resources, especially graphics cards, to enable better research.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:  "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:   true
resume_section_education:    true
resume_section_publications: true
resume_section_projects:     false
resume_section_recognition:  true
resume_section_skills:       true
resume_section_links:        true
resume_section_associations: false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:         "https://github.com/tkphd"
  resume_orcid_url:          "https://orcid.org/0000-0002-2920-8302"
  resume_website_url:        "http://www.trevorkeller.com"
  resume_twitter_url:        "http://twitter.com/tkphd"
  resume_scholar_url:        "https://scholar.google.com/citations?user=pHf0ImgAAAAJ&hl=en&oi=ao"
  resume_linkedin_url:       "https://www.linkedin.com/in/trevor-keller-a8610ba"
resume_print_social_links:   true

# Design settings
resume_theme:                default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
